### ISSUE TITLE
error relating to sun.audio

### ISSUE THREAD

**Issue by nanogram** [infrasparker/smashBros#1]
when attempting to run this, the new window shows up blank, but says:
**Exception in thread "main" java.lang.NoClassDefFoundError: sun/audio/AudioStream
        at src.smash.Smash.<init>(Smash.java:64)
        at Game.initialize(Game.java:51)
        at Game.run(Game.java:26)
        at Game.main(Game.java:21)
Caused by: java.lang.ClassNotFoundException: sun.audio.AudioStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 4 more**
not sure if this is bc I am using an newer version of java and maybe the sun.audio is depricated??

**Comment by infrasparker** [comment]
this project is pretty old, and yes your assumption is right. I haven't been updating the code at all for a long time. Sorry about that!7
